// Generated by ffca from Exchange.sol. Do not edit by hand.

declare const entrypoint: import("ffca").FFCASolidityEntrypoint<{
  readonly storageLayout: {
    readonly storage: readonly [
      {
        readonly astId: 42508;
        readonly contract: "src/Exchange.sol:Exchange";
        readonly label: "accounts";
        readonly offset: 0;
        readonly slot: "2";
        readonly type: "t_mapping(t_bytes32,t_struct(Account)42531_storage)";
      },
      {
        readonly astId: 42513;
        readonly contract: "src/Exchange.sol:Exchange";
        readonly label: "instruments";
        readonly offset: 0;
        readonly slot: "3";
        readonly type: "t_mapping(t_uint64,t_struct(Instrument)42565_storage)";
      },
    ];
    readonly types: {
      readonly t_address: {
        readonly encoding: "inplace";
        readonly label: "address";
        readonly numberOfBytes: "20";
      };
      readonly "t_array(t_struct(Key)42503_storage)dyn_storage": {
        readonly encoding: "dynamic_array";
        readonly label: "struct Key[]";
        readonly numberOfBytes: "32";
        readonly base: "t_struct(Key)42503_storage";
      };
      readonly "t_array(t_struct(Order)42542_storage)dyn_storage": {
        readonly encoding: "dynamic_array";
        readonly label: "struct Order[]";
        readonly numberOfBytes: "32";
        readonly base: "t_struct(Order)42542_storage";
      };
      readonly "t_array(t_struct(QueuedMutation)538_storage)dyn_storage": {
        readonly encoding: "dynamic_array";
        readonly label: "struct FFCA.QueuedMutation[]";
        readonly numberOfBytes: "32";
        readonly base: "t_struct(QueuedMutation)538_storage";
      };
      readonly t_bytes32: {
        readonly encoding: "inplace";
        readonly label: "bytes32";
        readonly numberOfBytes: "32";
      };
      readonly t_bytes_storage: {
        readonly encoding: "bytes";
        readonly label: "bytes";
        readonly numberOfBytes: "32";
      };
      readonly "t_enum(KeyType)5": {
        readonly encoding: "inplace";
        readonly label: "enum KeyType";
        readonly numberOfBytes: "1";
      };
      readonly "t_mapping(t_address,t_uint256)": {
        readonly encoding: "mapping";
        readonly key: "t_address";
        readonly label: "mapping(address => uint256)";
        readonly numberOfBytes: "32";
        readonly value: "t_uint256";
      };
      readonly "t_mapping(t_bytes32,t_struct(Account)42531_storage)": {
        readonly encoding: "mapping";
        readonly key: "t_bytes32";
        readonly label: "mapping(bytes32 => struct Account)";
        readonly numberOfBytes: "32";
        readonly value: "t_struct(Account)42531_storage";
      };
      readonly "t_mapping(t_uint192,t_uint64)": {
        readonly encoding: "mapping";
        readonly key: "t_uint192";
        readonly label: "mapping(uint192 => uint64)";
        readonly numberOfBytes: "32";
        readonly value: "t_uint64";
      };
      readonly "t_mapping(t_uint64,t_struct(Instrument)42565_storage)": {
        readonly encoding: "mapping";
        readonly key: "t_uint64";
        readonly label: "mapping(uint64 => struct Instrument)";
        readonly numberOfBytes: "32";
        readonly value: "t_struct(Instrument)42565_storage";
      };
      readonly "t_mapping(t_uint64,t_struct(Tick)42576_storage)": {
        readonly encoding: "mapping";
        readonly key: "t_uint64";
        readonly label: "mapping(uint64 => struct Tick)";
        readonly numberOfBytes: "32";
        readonly value: "t_struct(Tick)42576_storage";
      };
      readonly "t_struct(Account)42531_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Account";
        readonly numberOfBytes: "128";
        readonly members: readonly [
          {
            readonly astId: 42518;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "nonces";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_mapping(t_uint192,t_uint64)";
          },
          {
            readonly astId: 42522;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "balances";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_mapping(t_address,t_uint256)";
          },
          {
            readonly astId: 42526;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "keys";
            readonly offset: 0;
            readonly slot: "2";
            readonly type: "t_array(t_struct(Key)42503_storage)dyn_storage";
          },
          {
            readonly astId: 42530;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "orders";
            readonly offset: 0;
            readonly slot: "3";
            readonly type: "t_array(t_struct(Order)42542_storage)dyn_storage";
          },
        ];
      };
      readonly "t_struct(Instrument)42565_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Instrument";
        readonly numberOfBytes: "160";
        readonly members: readonly [
          {
            readonly astId: 42544;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "base";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_address";
          },
          {
            readonly astId: 42546;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "quote";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_address";
          },
          {
            readonly astId: 42548;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "baseLotExp";
            readonly offset: 20;
            readonly slot: "1";
            readonly type: "t_uint8";
          },
          {
            readonly astId: 42550;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "quoteLotExp";
            readonly offset: 21;
            readonly slot: "1";
            readonly type: "t_uint8";
          },
          {
            readonly astId: 42552;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "bestBid";
            readonly offset: 22;
            readonly slot: "1";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 42554;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "bestAsk";
            readonly offset: 0;
            readonly slot: "2";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 42559;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "bids";
            readonly offset: 0;
            readonly slot: "3";
            readonly type: "t_mapping(t_uint64,t_struct(Tick)42576_storage)";
          },
          {
            readonly astId: 42564;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "asks";
            readonly offset: 0;
            readonly slot: "4";
            readonly type: "t_mapping(t_uint64,t_struct(Tick)42576_storage)";
          },
        ];
      };
      readonly "t_struct(Key)42503_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Key";
        readonly numberOfBytes: "64";
        readonly members: readonly [
          {
            readonly astId: 42495;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "expiry";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint40";
          },
          {
            readonly astId: 42498;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "keyType";
            readonly offset: 5;
            readonly slot: "0";
            readonly type: "t_enum(KeyType)5";
          },
          {
            readonly astId: 42500;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "permissions";
            readonly offset: 6;
            readonly slot: "0";
            readonly type: "t_uint16";
          },
          {
            readonly astId: 42502;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "publicKey";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_bytes_storage";
          },
        ];
      };
      readonly "t_struct(Order)42542_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Order";
        readonly numberOfBytes: "32";
        readonly members: readonly [
          {
            readonly astId: 42533;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "quantity";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 42535;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "instrumentId";
            readonly offset: 8;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 42537;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "price";
            readonly offset: 16;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 42539;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "tickVolume";
            readonly offset: 24;
            readonly slot: "0";
            readonly type: "t_uint32";
          },
          {
            readonly astId: 42541;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "side";
            readonly offset: 28;
            readonly slot: "0";
            readonly type: "t_uint8";
          },
        ];
      };
      readonly "t_struct(QueuedMutation)538_storage": {
        readonly encoding: "inplace";
        readonly label: "struct FFCA.QueuedMutation";
        readonly numberOfBytes: "128";
        readonly members: readonly [
          {
            readonly astId: 531;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "mutation";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint8";
          },
          {
            readonly astId: 533;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "mutationData";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_bytes_storage";
          },
          {
            readonly astId: 535;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "signatureData";
            readonly offset: 0;
            readonly slot: "2";
            readonly type: "t_bytes_storage";
          },
          {
            readonly astId: 537;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "enqueuedBlock";
            readonly offset: 0;
            readonly slot: "3";
            readonly type: "t_uint256";
          },
        ];
      };
      readonly "t_struct(State)42514_storage": {
        readonly encoding: "inplace";
        readonly label: "struct State";
        readonly numberOfBytes: "64";
        readonly members: readonly [
          {
            readonly astId: 42508;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "accounts";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_mapping(t_bytes32,t_struct(Account)42531_storage)";
          },
          {
            readonly astId: 42513;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "instruments";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_mapping(t_uint64,t_struct(Instrument)42565_storage)";
          },
        ];
      };
      readonly "t_struct(Tick)42576_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Tick";
        readonly numberOfBytes: "64";
        readonly members: readonly [
          {
            readonly astId: 42567;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "quantity";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 42569;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "remainingQuantity";
            readonly offset: 8;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 42571;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "volume";
            readonly offset: 16;
            readonly slot: "0";
            readonly type: "t_uint32";
          },
          {
            readonly astId: 42573;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "prev";
            readonly offset: 20;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 42575;
            readonly contract: "src/Exchange.sol:Exchange";
            readonly label: "next";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_uint64";
          },
        ];
      };
      readonly t_uint16: {
        readonly encoding: "inplace";
        readonly label: "uint16";
        readonly numberOfBytes: "2";
      };
      readonly t_uint192: {
        readonly encoding: "inplace";
        readonly label: "uint192";
        readonly numberOfBytes: "24";
      };
      readonly t_uint256: {
        readonly encoding: "inplace";
        readonly label: "uint256";
        readonly numberOfBytes: "32";
      };
      readonly t_uint32: {
        readonly encoding: "inplace";
        readonly label: "uint32";
        readonly numberOfBytes: "4";
      };
      readonly t_uint40: {
        readonly encoding: "inplace";
        readonly label: "uint40";
        readonly numberOfBytes: "5";
      };
      readonly t_uint64: {
        readonly encoding: "inplace";
        readonly label: "uint64";
        readonly numberOfBytes: "8";
      };
      readonly t_uint8: {
        readonly encoding: "inplace";
        readonly label: "uint8";
        readonly numberOfBytes: "1";
      };
    };
  };
  readonly mutations: {
    readonly Initialize: {
      readonly tag: 0;
      readonly params: readonly [
        {
          readonly name: "account";
          readonly type: "bytes32";
        },
        {
          readonly name: "expiry";
          readonly type: "uint40";
        },
        {
          readonly name: "rootKeyType";
          readonly type: "uint8";
        },
        {
          readonly name: "keyType";
          readonly type: "uint8";
        },
        {
          readonly name: "permissions";
          readonly type: "uint16";
        },
        {
          readonly name: "rootPublicKey";
          readonly type: "bytes";
        },
        {
          readonly name: "publicKey";
          readonly type: "bytes";
        },
      ];
    };
    readonly Authorize: {
      readonly tag: 1;
      readonly params: readonly [
        {
          readonly name: "account";
          readonly type: "bytes32";
        },
        {
          readonly name: "expiry";
          readonly type: "uint40";
        },
        {
          readonly name: "keyType";
          readonly type: "uint8";
        },
        {
          readonly name: "permissions";
          readonly type: "uint16";
        },
        {
          readonly name: "publicKey";
          readonly type: "bytes";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly Revoke: {
      readonly tag: 2;
      readonly params: readonly [
        {
          readonly name: "account";
          readonly type: "bytes32";
        },
        {
          readonly name: "keyId";
          readonly type: "uint64";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly CloseOrder: {
      readonly tag: 3;
      readonly params: readonly [
        {
          readonly name: "orderId";
          readonly type: "uint64";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly ChangeOrder: {
      readonly tag: 4;
      readonly params: readonly [
        {
          readonly name: "orderId";
          readonly type: "uint64";
        },
        {
          readonly name: "price";
          readonly type: "uint64";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly LimitOrder: {
      readonly tag: 5;
      readonly params: readonly [
        {
          readonly name: "quantity";
          readonly type: "uint256";
        },
        {
          readonly name: "instrumentId";
          readonly type: "uint64";
        },
        {
          readonly name: "price";
          readonly type: "uint64";
        },
        {
          readonly name: "bidOrAsk";
          readonly type: "uint8";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly MarketOrder: {
      readonly tag: 6;
      readonly params: readonly [
        {
          readonly name: "quantity";
          readonly type: "uint256";
        },
        {
          readonly name: "minReceivedQuantity";
          readonly type: "uint256";
        },
        {
          readonly name: "instrumentId";
          readonly type: "uint64";
        },
        {
          readonly name: "bidOrAsk";
          readonly type: "uint8";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly AddInstrument: {
      readonly tag: 7;
      readonly params: readonly [
        {
          readonly name: "instrumentId";
          readonly type: "uint64";
        },
        {
          readonly name: "base";
          readonly type: "address";
        },
        {
          readonly name: "quote";
          readonly type: "address";
        },
        {
          readonly name: "baseLotExp";
          readonly type: "uint8";
        },
        {
          readonly name: "quoteLotExp";
          readonly type: "uint8";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly Deposit: {
      readonly tag: 8;
      readonly params: readonly [
        {
          readonly name: "asset";
          readonly type: "address";
        },
        {
          readonly name: "amount";
          readonly type: "uint256";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly Withdrawal: {
      readonly tag: 9;
      readonly params: readonly [
        {
          readonly name: "asset";
          readonly type: "address";
        },
        {
          readonly name: "amount";
          readonly type: "uint256";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
  };
  readonly signature: readonly [
    {
      readonly name: "account";
      readonly type: "bytes32";
    },
    {
      readonly name: "keyId";
      readonly type: "uint64";
    },
    {
      readonly name: "rawSignature";
      readonly type: "bytes";
    },
  ];
}>;
export default entrypoint;
