// Generated by typewriter from OrderBook.sol. Do not edit by hand.

declare const entrypoint: import("typewriter").TypewriterSolidityEntrypoint<{
  readonly storageLayout: {
    readonly storage: readonly [
      {
        readonly astId: 694;
        readonly contract: "src/OrderBook.sol:OrderBook";
        readonly label: "accounts";
        readonly offset: 0;
        readonly slot: "0";
        readonly type: "t_mapping(t_bytes32,t_struct(Account)26_storage)";
      },
      {
        readonly astId: 698;
        readonly contract: "src/OrderBook.sol:OrderBook";
        readonly label: "queue";
        readonly offset: 0;
        readonly slot: "1";
        readonly type: "t_array(t_struct(QueuedMutation)657_storage)dyn_storage";
      },
      {
        readonly astId: 700;
        readonly contract: "src/OrderBook.sol:OrderBook";
        readonly label: "executionIndex";
        readonly offset: 0;
        readonly slot: "2";
        readonly type: "t_uint256";
      },
      {
        readonly astId: 43903;
        readonly contract: "src/OrderBook.sol:OrderBook";
        readonly label: "state";
        readonly offset: 0;
        readonly slot: "3";
        readonly type: "t_struct(State)43420_storage";
      },
    ];
    readonly types: {
      readonly t_address: {
        readonly encoding: "inplace";
        readonly label: "address";
        readonly numberOfBytes: "20";
      };
      readonly "t_array(t_struct(Credential)15_storage)dyn_storage": {
        readonly encoding: "dynamic_array";
        readonly label: "struct Credential[]";
        readonly numberOfBytes: "32";
        readonly base: "t_struct(Credential)15_storage";
      };
      readonly "t_array(t_struct(Order)43440_storage)dyn_storage": {
        readonly encoding: "dynamic_array";
        readonly label: "struct Order[]";
        readonly numberOfBytes: "32";
        readonly base: "t_struct(Order)43440_storage";
      };
      readonly "t_array(t_struct(QueuedMutation)657_storage)dyn_storage": {
        readonly encoding: "dynamic_array";
        readonly label: "struct Typewriter.QueuedMutation[]";
        readonly numberOfBytes: "32";
        readonly base: "t_struct(QueuedMutation)657_storage";
      };
      readonly t_bytes32: {
        readonly encoding: "inplace";
        readonly label: "bytes32";
        readonly numberOfBytes: "32";
      };
      readonly t_bytes_storage: {
        readonly encoding: "bytes";
        readonly label: "bytes";
        readonly numberOfBytes: "32";
      };
      readonly "t_enum(KeyType)5": {
        readonly encoding: "inplace";
        readonly label: "enum KeyType";
        readonly numberOfBytes: "1";
      };
      readonly "t_mapping(t_address,t_uint256)": {
        readonly encoding: "mapping";
        readonly key: "t_address";
        readonly label: "mapping(address => uint256)";
        readonly numberOfBytes: "32";
        readonly value: "t_uint256";
      };
      readonly "t_mapping(t_bytes32,t_struct(Account)26_storage)": {
        readonly encoding: "mapping";
        readonly key: "t_bytes32";
        readonly label: "mapping(bytes32 => struct Account)";
        readonly numberOfBytes: "32";
        readonly value: "t_struct(Account)26_storage";
      };
      readonly "t_mapping(t_bytes32,t_struct(Account)43429_storage)": {
        readonly encoding: "mapping";
        readonly key: "t_bytes32";
        readonly label: "mapping(bytes32 => struct Account)";
        readonly numberOfBytes: "32";
        readonly value: "t_struct(Account)43429_storage";
      };
      readonly "t_mapping(t_uint192,t_uint64)": {
        readonly encoding: "mapping";
        readonly key: "t_uint192";
        readonly label: "mapping(uint192 => uint64)";
        readonly numberOfBytes: "32";
        readonly value: "t_uint64";
      };
      readonly "t_mapping(t_uint64,t_struct(Instrument)43463_storage)": {
        readonly encoding: "mapping";
        readonly key: "t_uint64";
        readonly label: "mapping(uint64 => struct Instrument)";
        readonly numberOfBytes: "32";
        readonly value: "t_struct(Instrument)43463_storage";
      };
      readonly "t_mapping(t_uint64,t_struct(Tick)43474_storage)": {
        readonly encoding: "mapping";
        readonly key: "t_uint64";
        readonly label: "mapping(uint64 => struct Tick)";
        readonly numberOfBytes: "32";
        readonly value: "t_struct(Tick)43474_storage";
      };
      readonly "t_struct(Account)26_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Account";
        readonly numberOfBytes: "96";
        readonly members: readonly [
          {
            readonly astId: 19;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "nonces";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_mapping(t_uint192,t_uint64)";
          },
          {
            readonly astId: 23;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "credentials";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_array(t_struct(Credential)15_storage)dyn_storage";
          },
          {
            readonly astId: 25;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "activeCredentials";
            readonly offset: 0;
            readonly slot: "2";
            readonly type: "t_uint64";
          },
        ];
      };
      readonly "t_struct(Account)43429_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Account";
        readonly numberOfBytes: "64";
        readonly members: readonly [
          {
            readonly astId: 43424;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "balances";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_mapping(t_address,t_uint256)";
          },
          {
            readonly astId: 43428;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "orders";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_array(t_struct(Order)43440_storage)dyn_storage";
          },
        ];
      };
      readonly "t_struct(Credential)15_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Credential";
        readonly numberOfBytes: "96";
        readonly members: readonly [
          {
            readonly astId: 7;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "expiration";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint40";
          },
          {
            readonly astId: 10;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "keyType";
            readonly offset: 5;
            readonly slot: "0";
            readonly type: "t_enum(KeyType)5";
          },
          {
            readonly astId: 12;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "permissions";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_uint256";
          },
          {
            readonly astId: 14;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "publicKey";
            readonly offset: 0;
            readonly slot: "2";
            readonly type: "t_bytes_storage";
          },
        ];
      };
      readonly "t_struct(Instrument)43463_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Instrument";
        readonly numberOfBytes: "160";
        readonly members: readonly [
          {
            readonly astId: 43442;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "base";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_address";
          },
          {
            readonly astId: 43444;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "quote";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_address";
          },
          {
            readonly astId: 43446;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "baseLotExp";
            readonly offset: 20;
            readonly slot: "1";
            readonly type: "t_uint8";
          },
          {
            readonly astId: 43448;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "quoteLotExp";
            readonly offset: 21;
            readonly slot: "1";
            readonly type: "t_uint8";
          },
          {
            readonly astId: 43450;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "bestBid";
            readonly offset: 22;
            readonly slot: "1";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 43452;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "bestAsk";
            readonly offset: 0;
            readonly slot: "2";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 43457;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "bids";
            readonly offset: 0;
            readonly slot: "3";
            readonly type: "t_mapping(t_uint64,t_struct(Tick)43474_storage)";
          },
          {
            readonly astId: 43462;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "asks";
            readonly offset: 0;
            readonly slot: "4";
            readonly type: "t_mapping(t_uint64,t_struct(Tick)43474_storage)";
          },
        ];
      };
      readonly "t_struct(Order)43440_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Order";
        readonly numberOfBytes: "32";
        readonly members: readonly [
          {
            readonly astId: 43431;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "quantity";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 43433;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "instrumentId";
            readonly offset: 8;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 43435;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "price";
            readonly offset: 16;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 43437;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "tickVolume";
            readonly offset: 24;
            readonly slot: "0";
            readonly type: "t_uint32";
          },
          {
            readonly astId: 43439;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "side";
            readonly offset: 28;
            readonly slot: "0";
            readonly type: "t_uint8";
          },
        ];
      };
      readonly "t_struct(QueuedMutation)657_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Typewriter.QueuedMutation";
        readonly numberOfBytes: "128";
        readonly members: readonly [
          {
            readonly astId: 650;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "mutation";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint8";
          },
          {
            readonly astId: 652;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "mutationData";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_bytes_storage";
          },
          {
            readonly astId: 654;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "authorizationData";
            readonly offset: 0;
            readonly slot: "2";
            readonly type: "t_bytes_storage";
          },
          {
            readonly astId: 656;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "enqueuedBlock";
            readonly offset: 0;
            readonly slot: "3";
            readonly type: "t_uint256";
          },
        ];
      };
      readonly "t_struct(State)43420_storage": {
        readonly encoding: "inplace";
        readonly label: "struct State";
        readonly numberOfBytes: "64";
        readonly members: readonly [
          {
            readonly astId: 43414;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "accounts";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_mapping(t_bytes32,t_struct(Account)43429_storage)";
          },
          {
            readonly astId: 43419;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "instruments";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_mapping(t_uint64,t_struct(Instrument)43463_storage)";
          },
        ];
      };
      readonly "t_struct(Tick)43474_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Tick";
        readonly numberOfBytes: "64";
        readonly members: readonly [
          {
            readonly astId: 43465;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "quantity";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 43467;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "remainingQuantity";
            readonly offset: 8;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 43469;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "volume";
            readonly offset: 16;
            readonly slot: "0";
            readonly type: "t_uint32";
          },
          {
            readonly astId: 43471;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "prev";
            readonly offset: 20;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 43473;
            readonly contract: "src/OrderBook.sol:OrderBook";
            readonly label: "next";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_uint64";
          },
        ];
      };
      readonly t_uint192: {
        readonly encoding: "inplace";
        readonly label: "uint192";
        readonly numberOfBytes: "24";
      };
      readonly t_uint256: {
        readonly encoding: "inplace";
        readonly label: "uint256";
        readonly numberOfBytes: "32";
      };
      readonly t_uint32: {
        readonly encoding: "inplace";
        readonly label: "uint32";
        readonly numberOfBytes: "4";
      };
      readonly t_uint40: {
        readonly encoding: "inplace";
        readonly label: "uint40";
        readonly numberOfBytes: "5";
      };
      readonly t_uint64: {
        readonly encoding: "inplace";
        readonly label: "uint64";
        readonly numberOfBytes: "8";
      };
      readonly t_uint8: {
        readonly encoding: "inplace";
        readonly label: "uint8";
        readonly numberOfBytes: "1";
      };
    };
  };
  readonly mutations: {
    readonly CloseOrder: {
      readonly id: 0;
      readonly params: readonly [
        {
          readonly name: "orderId";
          readonly type: "uint64";
        },
      ];
    };
    readonly ChangeOrder: {
      readonly id: 1;
      readonly params: readonly [
        {
          readonly name: "orderId";
          readonly type: "uint64";
        },
        {
          readonly name: "price";
          readonly type: "uint64";
        },
      ];
    };
    readonly LimitOrder: {
      readonly id: 2;
      readonly params: readonly [
        {
          readonly name: "quantity";
          readonly type: "uint256";
        },
        {
          readonly name: "instrumentId";
          readonly type: "uint64";
        },
        {
          readonly name: "price";
          readonly type: "uint64";
        },
        {
          readonly name: "bidOrAsk";
          readonly type: "uint8";
        },
      ];
    };
    readonly MarketOrder: {
      readonly id: 3;
      readonly params: readonly [
        {
          readonly name: "quantity";
          readonly type: "uint256";
        },
        {
          readonly name: "minReceivedQuantity";
          readonly type: "uint256";
        },
        {
          readonly name: "instrumentId";
          readonly type: "uint64";
        },
        {
          readonly name: "bidOrAsk";
          readonly type: "uint8";
        },
      ];
    };
    readonly AddInstrument: {
      readonly id: 4;
      readonly params: readonly [
        {
          readonly name: "instrumentId";
          readonly type: "uint64";
        },
        {
          readonly name: "base";
          readonly type: "address";
        },
        {
          readonly name: "quote";
          readonly type: "address";
        },
        {
          readonly name: "baseLotExp";
          readonly type: "uint8";
        },
        {
          readonly name: "quoteLotExp";
          readonly type: "uint8";
        },
      ];
    };
    readonly Deposit: {
      readonly id: 5;
      readonly params: readonly [
        {
          readonly name: "asset";
          readonly type: "address";
        },
        {
          readonly name: "amount";
          readonly type: "uint256";
        },
      ];
    };
    readonly Withdrawal: {
      readonly id: 6;
      readonly params: readonly [
        {
          readonly name: "asset";
          readonly type: "address";
        },
        {
          readonly name: "amount";
          readonly type: "uint256";
        },
      ];
    };
    readonly CreateAccount: {
      readonly id: 253;
      readonly params: readonly [
        {
          readonly name: "keyType";
          readonly type: "uint8";
        },
        {
          readonly name: "publicKey";
          readonly type: "bytes";
        },
      ];
    };
    readonly AddCredential: {
      readonly id: 254;
      readonly params: readonly [
        {
          readonly name: "expiration";
          readonly type: "uint40";
        },
        {
          readonly name: "keyType";
          readonly type: "uint8";
        },
        {
          readonly name: "permissions";
          readonly type: "uint256";
        },
        {
          readonly name: "publicKey";
          readonly type: "bytes";
        },
      ];
    };
    readonly RemoveCredential: {
      readonly id: 255;
      readonly params: readonly [
        {
          readonly name: "credentialID";
          readonly type: "uint64";
        },
      ];
    };
  };
}>;
export default entrypoint;
