[profile.default]
src = "src"
out = "out"
libs = ["../node_modules", "node_modules"]
allow_paths = ["../node_modules", "../node_modules/forge-std/src", "../../../packages/typewriter/src"]
isolate = true
optimizer = true
optimizer_runs = 200
extra_output = ["storageLayout"]
