// Generated by typewriter from PixelWar.sol. Do not edit by hand.

declare const entrypoint: import("typewriter").TypewriterSolidityEntrypoint<{
  readonly storageLayout: {
    readonly storage: readonly [
      {
        readonly astId: 42465;
        readonly contract: "src/PixelWar.sol:PixelWar";
        readonly label: "epoch";
        readonly offset: 0;
        readonly slot: "2";
        readonly type: "t_uint64";
      },
      {
        readonly astId: 42470;
        readonly contract: "src/PixelWar.sol:PixelWar";
        readonly label: "accounts";
        readonly offset: 0;
        readonly slot: "3";
        readonly type: "t_mapping(t_bytes32,t_struct(Account)42463_storage)";
      },
      {
        readonly astId: 42474;
        readonly contract: "src/PixelWar.sol:PixelWar";
        readonly label: "canvas";
        readonly offset: 0;
        readonly slot: "4";
        readonly type: "t_array(t_uint256)256_storage";
      },
      {
        readonly astId: 42478;
        readonly contract: "src/PixelWar.sol:PixelWar";
        readonly label: "shields";
        readonly offset: 0;
        readonly slot: "260";
        readonly type: "t_mapping(t_uint32,t_uint8)";
      },
      {
        readonly astId: 42482;
        readonly contract: "src/PixelWar.sol:PixelWar";
        readonly label: "teamPixels";
        readonly offset: 0;
        readonly slot: "261";
        readonly type: "t_array(t_uint32)4_storage";
      },
      {
        readonly astId: 42486;
        readonly contract: "src/PixelWar.sol:PixelWar";
        readonly label: "teamPlayers";
        readonly offset: 0;
        readonly slot: "262";
        readonly type: "t_array(t_uint32)4_storage";
      },
    ];
    readonly types: {
      readonly "t_array(t_struct(Key)42446_storage)dyn_storage": {
        readonly encoding: "dynamic_array";
        readonly label: "struct Key[]";
        readonly numberOfBytes: "32";
        readonly base: "t_struct(Key)42446_storage";
      };
      readonly "t_array(t_struct(QueuedMutation)538_storage)dyn_storage": {
        readonly encoding: "dynamic_array";
        readonly label: "struct Typewriter.QueuedMutation[]";
        readonly numberOfBytes: "32";
        readonly base: "t_struct(QueuedMutation)538_storage";
      };
      readonly "t_array(t_uint256)256_storage": {
        readonly encoding: "inplace";
        readonly label: "uint256[256]";
        readonly numberOfBytes: "8192";
        readonly base: "t_uint256";
      };
      readonly "t_array(t_uint32)4_storage": {
        readonly encoding: "inplace";
        readonly label: "uint32[4]";
        readonly numberOfBytes: "32";
        readonly base: "t_uint32";
      };
      readonly t_bytes32: {
        readonly encoding: "inplace";
        readonly label: "bytes32";
        readonly numberOfBytes: "32";
      };
      readonly t_bytes_storage: {
        readonly encoding: "bytes";
        readonly label: "bytes";
        readonly numberOfBytes: "32";
      };
      readonly "t_enum(KeyType)5": {
        readonly encoding: "inplace";
        readonly label: "enum KeyType";
        readonly numberOfBytes: "1";
      };
      readonly "t_mapping(t_bytes32,t_struct(Account)42463_storage)": {
        readonly encoding: "mapping";
        readonly key: "t_bytes32";
        readonly label: "mapping(bytes32 => struct Account)";
        readonly numberOfBytes: "32";
        readonly value: "t_struct(Account)42463_storage";
      };
      readonly "t_mapping(t_uint192,t_uint64)": {
        readonly encoding: "mapping";
        readonly key: "t_uint192";
        readonly label: "mapping(uint192 => uint64)";
        readonly numberOfBytes: "32";
        readonly value: "t_uint64";
      };
      readonly "t_mapping(t_uint32,t_uint8)": {
        readonly encoding: "mapping";
        readonly key: "t_uint32";
        readonly label: "mapping(uint32 => uint8)";
        readonly numberOfBytes: "32";
        readonly value: "t_uint8";
      };
      readonly "t_struct(Account)42463_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Account";
        readonly numberOfBytes: "96";
        readonly members: readonly [
          {
            readonly astId: 42448;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "epoch";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 42450;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "energy";
            readonly offset: 8;
            readonly slot: "0";
            readonly type: "t_uint32";
          },
          {
            readonly astId: 42452;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "painted";
            readonly offset: 12;
            readonly slot: "0";
            readonly type: "t_uint32";
          },
          {
            readonly astId: 42454;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "team";
            readonly offset: 16;
            readonly slot: "0";
            readonly type: "t_uint8";
          },
          {
            readonly astId: 42458;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "keys";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_array(t_struct(Key)42446_storage)dyn_storage";
          },
          {
            readonly astId: 42462;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "nonces";
            readonly offset: 0;
            readonly slot: "2";
            readonly type: "t_mapping(t_uint192,t_uint64)";
          },
        ];
      };
      readonly "t_struct(Key)42446_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Key";
        readonly numberOfBytes: "64";
        readonly members: readonly [
          {
            readonly astId: 42438;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "expiry";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint40";
          },
          {
            readonly astId: 42441;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "keyType";
            readonly offset: 5;
            readonly slot: "0";
            readonly type: "t_enum(KeyType)5";
          },
          {
            readonly astId: 42443;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "permissions";
            readonly offset: 6;
            readonly slot: "0";
            readonly type: "t_uint16";
          },
          {
            readonly astId: 42445;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "publicKey";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_bytes_storage";
          },
        ];
      };
      readonly "t_struct(QueuedMutation)538_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Typewriter.QueuedMutation";
        readonly numberOfBytes: "128";
        readonly members: readonly [
          {
            readonly astId: 531;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "mutation";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint8";
          },
          {
            readonly astId: 533;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "mutationData";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_bytes_storage";
          },
          {
            readonly astId: 535;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "signatureData";
            readonly offset: 0;
            readonly slot: "2";
            readonly type: "t_bytes_storage";
          },
          {
            readonly astId: 537;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "enqueuedBlock";
            readonly offset: 0;
            readonly slot: "3";
            readonly type: "t_uint256";
          },
        ];
      };
      readonly "t_struct(State)42487_storage": {
        readonly encoding: "inplace";
        readonly label: "struct State";
        readonly numberOfBytes: "8352";
        readonly members: readonly [
          {
            readonly astId: 42465;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "epoch";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint64";
          },
          {
            readonly astId: 42470;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "accounts";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_mapping(t_bytes32,t_struct(Account)42463_storage)";
          },
          {
            readonly astId: 42474;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "canvas";
            readonly offset: 0;
            readonly slot: "2";
            readonly type: "t_array(t_uint256)256_storage";
          },
          {
            readonly astId: 42478;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "shields";
            readonly offset: 0;
            readonly slot: "258";
            readonly type: "t_mapping(t_uint32,t_uint8)";
          },
          {
            readonly astId: 42482;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "teamPixels";
            readonly offset: 0;
            readonly slot: "259";
            readonly type: "t_array(t_uint32)4_storage";
          },
          {
            readonly astId: 42486;
            readonly contract: "src/PixelWar.sol:PixelWar";
            readonly label: "teamPlayers";
            readonly offset: 0;
            readonly slot: "260";
            readonly type: "t_array(t_uint32)4_storage";
          },
        ];
      };
      readonly t_uint16: {
        readonly encoding: "inplace";
        readonly label: "uint16";
        readonly numberOfBytes: "2";
      };
      readonly t_uint192: {
        readonly encoding: "inplace";
        readonly label: "uint192";
        readonly numberOfBytes: "24";
      };
      readonly t_uint256: {
        readonly encoding: "inplace";
        readonly label: "uint256";
        readonly numberOfBytes: "32";
      };
      readonly t_uint32: {
        readonly encoding: "inplace";
        readonly label: "uint32";
        readonly numberOfBytes: "4";
      };
      readonly t_uint40: {
        readonly encoding: "inplace";
        readonly label: "uint40";
        readonly numberOfBytes: "5";
      };
      readonly t_uint64: {
        readonly encoding: "inplace";
        readonly label: "uint64";
        readonly numberOfBytes: "8";
      };
      readonly t_uint8: {
        readonly encoding: "inplace";
        readonly label: "uint8";
        readonly numberOfBytes: "1";
      };
    };
  };
  readonly mutations: {
    readonly Initialize: {
      readonly tag: 0;
      readonly params: readonly [
        {
          readonly name: "account";
          readonly type: "bytes32";
        },
        {
          readonly name: "expiry";
          readonly type: "uint40";
        },
        {
          readonly name: "rootKeyType";
          readonly type: "uint8";
        },
        {
          readonly name: "keyType";
          readonly type: "uint8";
        },
        {
          readonly name: "permissions";
          readonly type: "uint16";
        },
        {
          readonly name: "rootPublicKey";
          readonly type: "bytes";
        },
        {
          readonly name: "publicKey";
          readonly type: "bytes";
        },
      ];
    };
    readonly Authorize: {
      readonly tag: 1;
      readonly params: readonly [
        {
          readonly name: "account";
          readonly type: "bytes32";
        },
        {
          readonly name: "expiry";
          readonly type: "uint40";
        },
        {
          readonly name: "keyType";
          readonly type: "uint8";
        },
        {
          readonly name: "permissions";
          readonly type: "uint16";
        },
        {
          readonly name: "publicKey";
          readonly type: "bytes";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly Revoke: {
      readonly tag: 2;
      readonly params: readonly [
        {
          readonly name: "account";
          readonly type: "bytes32";
        },
        {
          readonly name: "keyId";
          readonly type: "uint64";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly AdvanceEpoch: {
      readonly tag: 3;
      readonly params: readonly [
        {
          readonly name: "epoch";
          readonly type: "uint64";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly Shield: {
      readonly tag: 4;
      readonly params: readonly [
        {
          readonly name: "x";
          readonly type: "uint16";
        },
        {
          readonly name: "y";
          readonly type: "uint16";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly Paint: {
      readonly tag: 5;
      readonly params: readonly [
        {
          readonly name: "x";
          readonly type: "uint16";
        },
        {
          readonly name: "y";
          readonly type: "uint16";
        },
        {
          readonly name: "color";
          readonly type: "uint8";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly Bomb: {
      readonly tag: 6;
      readonly params: readonly [
        {
          readonly name: "x";
          readonly type: "uint16";
        },
        {
          readonly name: "y";
          readonly type: "uint16";
        },
        {
          readonly name: "color";
          readonly type: "uint8";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
  };
  readonly signature: readonly [
    {
      readonly name: "account";
      readonly type: "bytes32";
    },
    {
      readonly name: "keyId";
      readonly type: "uint64";
    },
    {
      readonly name: "rawSignature";
      readonly type: "bytes";
    },
  ];
}>;
export default entrypoint;
