// Generated by typewriter from Token.sol. Do not edit by hand.

declare const entrypoint: import("typewriter").TypewriterSolidityEntrypoint<{
  readonly storageLayout: {
    readonly storage: readonly [
      {
        readonly astId: 41569;
        readonly contract: "src/Token.sol:Token";
        readonly label: "totalSupply";
        readonly offset: 0;
        readonly slot: "2";
        readonly type: "t_uint256";
      },
      {
        readonly astId: 41574;
        readonly contract: "src/Token.sol:Token";
        readonly label: "accounts";
        readonly offset: 0;
        readonly slot: "3";
        readonly type: "t_mapping(t_address,t_struct(Account)41567_storage)";
      },
    ];
    readonly types: {
      readonly t_address: {
        readonly encoding: "inplace";
        readonly label: "address";
        readonly numberOfBytes: "20";
      };
      readonly "t_array(t_struct(QueuedMutation)538_storage)dyn_storage": {
        readonly encoding: "dynamic_array";
        readonly label: "struct Typewriter.QueuedMutation[]";
        readonly numberOfBytes: "32";
        readonly base: "t_struct(QueuedMutation)538_storage";
      };
      readonly t_bytes_storage: {
        readonly encoding: "bytes";
        readonly label: "bytes";
        readonly numberOfBytes: "32";
      };
      readonly "t_mapping(t_address,t_struct(Account)41567_storage)": {
        readonly encoding: "mapping";
        readonly key: "t_address";
        readonly label: "mapping(address => struct Account)";
        readonly numberOfBytes: "32";
        readonly value: "t_struct(Account)41567_storage";
      };
      readonly "t_struct(Account)41567_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Account";
        readonly numberOfBytes: "64";
        readonly members: readonly [
          {
            readonly astId: 41564;
            readonly contract: "src/Token.sol:Token";
            readonly label: "nonce";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint256";
          },
          {
            readonly astId: 41566;
            readonly contract: "src/Token.sol:Token";
            readonly label: "balance";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_uint256";
          },
        ];
      };
      readonly "t_struct(QueuedMutation)538_storage": {
        readonly encoding: "inplace";
        readonly label: "struct Typewriter.QueuedMutation";
        readonly numberOfBytes: "128";
        readonly members: readonly [
          {
            readonly astId: 531;
            readonly contract: "src/Token.sol:Token";
            readonly label: "mutation";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint8";
          },
          {
            readonly astId: 533;
            readonly contract: "src/Token.sol:Token";
            readonly label: "mutationData";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_bytes_storage";
          },
          {
            readonly astId: 535;
            readonly contract: "src/Token.sol:Token";
            readonly label: "signatureData";
            readonly offset: 0;
            readonly slot: "2";
            readonly type: "t_bytes_storage";
          },
          {
            readonly astId: 537;
            readonly contract: "src/Token.sol:Token";
            readonly label: "enqueuedBlock";
            readonly offset: 0;
            readonly slot: "3";
            readonly type: "t_uint256";
          },
        ];
      };
      readonly "t_struct(State)41575_storage": {
        readonly encoding: "inplace";
        readonly label: "struct State";
        readonly numberOfBytes: "64";
        readonly members: readonly [
          {
            readonly astId: 41569;
            readonly contract: "src/Token.sol:Token";
            readonly label: "totalSupply";
            readonly offset: 0;
            readonly slot: "0";
            readonly type: "t_uint256";
          },
          {
            readonly astId: 41574;
            readonly contract: "src/Token.sol:Token";
            readonly label: "accounts";
            readonly offset: 0;
            readonly slot: "1";
            readonly type: "t_mapping(t_address,t_struct(Account)41567_storage)";
          },
        ];
      };
      readonly t_uint256: {
        readonly encoding: "inplace";
        readonly label: "uint256";
        readonly numberOfBytes: "32";
      };
      readonly t_uint8: {
        readonly encoding: "inplace";
        readonly label: "uint8";
        readonly numberOfBytes: "1";
      };
    };
  };
  readonly mutations: {
    readonly Transfer: {
      readonly tag: 0;
      readonly params: readonly [
        {
          readonly name: "from";
          readonly type: "address";
        },
        {
          readonly name: "to";
          readonly type: "address";
        },
        {
          readonly name: "amount";
          readonly type: "uint256";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
    readonly Mint: {
      readonly tag: 1;
      readonly params: readonly [
        {
          readonly name: "to";
          readonly type: "address";
        },
        {
          readonly name: "amount";
          readonly type: "uint256";
        },
        {
          readonly name: "nonce";
          readonly type: "uint256";
        },
        {
          readonly name: "deadline";
          readonly type: "uint256";
        },
      ];
    };
  };
  readonly signature: readonly [
    {
      readonly name: "keyType";
      readonly type: "uint8";
    },
    {
      readonly name: "rawSignature";
      readonly type: "bytes";
    },
  ];
}>;
export default entrypoint;
