// Writes each fixture's ABI, bytecode, and `storageLayout` from the Foundry
// output to `test/contracts/generated.ts` as `as const` literals.

import { Glob } from "bun";

const contractsDir = `${import.meta.dir}/../test/contracts`;
const generatedPath = `${contractsDir}/generated.ts`;

type ForgeArtifact = {
  abi: unknown;
  bytecode: { object: string };
  storageLayout?: unknown;
};

let output =
  "// Generated by `scripts/generateTypedArtifacts.ts`. Do not edit.\n\n";

const sourceFiles = await Array.fromAsync(
  new Glob("*.sol").scan(`${contractsDir}/src`),
);
for (const sourceFile of sourceFiles.sort()) {
  const artifacts = await Array.fromAsync(
    new Glob("*.json").scan(`${contractsDir}/out/${sourceFile}`),
  );
  for (const artifactFile of artifacts.sort()) {
    const name = artifactFile.replace(/\.json$/, "");
    const { abi, bytecode, storageLayout }: ForgeArtifact = await Bun.file(
      `${contractsDir}/out/${sourceFile}/${artifactFile}`,
    ).json();
    if (storageLayout === undefined) {
      throw new Error(
        `${sourceFile}:${name} has no storageLayout. Is extra_output set in foundry.toml?`,
      );
    }
    const artifact = { abi, bytecode: bytecode.object, storageLayout };
    output += `export const ${name} = ${JSON.stringify(artifact, null, 2)} as const;\n\n`;
  }
}

await Bun.write(generatedPath, output);
