import type { StorageLayout } from "storage-layout";

// Copied from forge's generated `storageLayout` and flattened to the app-owned
// Exchange.State shape used by the runtime.
export const EXCHANGE_STORAGE_LAYOUT = {
  storage: [
    {
      astId: 41381,
      contract: "src/Exchange.sol:Exchange",
      label: "accounts",
      offset: 0,
      slot: "0",
      type: "t_mapping(t_bytes32,t_struct(Account)41404_storage)",
    },
    {
      astId: 41386,
      contract: "src/Exchange.sol:Exchange",
      label: "instruments",
      offset: 0,
      slot: "1",
      type: "t_mapping(t_uint64,t_struct(Instrument)41434_storage)",
    },
  ],
  types: {
    t_address: { encoding: "inplace", label: "address", numberOfBytes: "20" },
    "t_array(t_struct(Key)41376_storage)dyn_storage": {
      encoding: "dynamic_array",
      label: "struct Key[]",
      numberOfBytes: "32",
      base: "t_struct(Key)41376_storage",
    },
    "t_array(t_struct(Order)41415_storage)dyn_storage": {
      encoding: "dynamic_array",
      label: "struct Order[]",
      numberOfBytes: "32",
      base: "t_struct(Order)41415_storage",
    },
    "t_array(t_struct(QueuedMutation)41606_storage)dyn_storage": {
      encoding: "dynamic_array",
      label: "struct QueuedMutation[]",
      numberOfBytes: "32",
      base: "t_struct(QueuedMutation)41606_storage",
    },
    t_bytes32: { encoding: "inplace", label: "bytes32", numberOfBytes: "32" },
    t_bytes_storage: { encoding: "bytes", label: "bytes", numberOfBytes: "32" },
    "t_enum(KeyType)5": {
      encoding: "inplace",
      label: "enum KeyType",
      numberOfBytes: "1",
    },
    "t_enum(Mutation)41452": {
      encoding: "inplace",
      label: "enum Mutation",
      numberOfBytes: "1",
    },
    "t_mapping(t_address,t_uint256)": {
      encoding: "mapping",
      key: "t_address",
      label: "mapping(address => uint256)",
      numberOfBytes: "32",
      value: "t_uint256",
    },
    "t_mapping(t_bytes32,t_struct(Account)41404_storage)": {
      encoding: "mapping",
      key: "t_bytes32",
      label: "mapping(bytes32 => struct Account)",
      numberOfBytes: "32",
      value: "t_struct(Account)41404_storage",
    },
    "t_mapping(t_uint192,t_uint64)": {
      encoding: "mapping",
      key: "t_uint192",
      label: "mapping(uint192 => uint64)",
      numberOfBytes: "32",
      value: "t_uint64",
    },
    "t_mapping(t_uint64,t_struct(Instrument)41434_storage)": {
      encoding: "mapping",
      key: "t_uint64",
      label: "mapping(uint64 => struct Instrument)",
      numberOfBytes: "32",
      value: "t_struct(Instrument)41434_storage",
    },
    "t_mapping(t_uint64,t_struct(Tick)41441_storage)": {
      encoding: "mapping",
      key: "t_uint64",
      label: "mapping(uint64 => struct Tick)",
      numberOfBytes: "32",
      value: "t_struct(Tick)41441_storage",
    },
    "t_struct(Account)41404_storage": {
      encoding: "inplace",
      label: "struct Account",
      numberOfBytes: "128",
      members: [
        {
          astId: 41391,
          contract: "src/Exchange.sol:Exchange",
          label: "nonces",
          offset: 0,
          slot: "0",
          type: "t_mapping(t_uint192,t_uint64)",
        },
        {
          astId: 41395,
          contract: "src/Exchange.sol:Exchange",
          label: "balances",
          offset: 0,
          slot: "1",
          type: "t_mapping(t_address,t_uint256)",
        },
        {
          astId: 41399,
          contract: "src/Exchange.sol:Exchange",
          label: "keys",
          offset: 0,
          slot: "2",
          type: "t_array(t_struct(Key)41376_storage)dyn_storage",
        },
        {
          astId: 41403,
          contract: "src/Exchange.sol:Exchange",
          label: "orders",
          offset: 0,
          slot: "3",
          type: "t_array(t_struct(Order)41415_storage)dyn_storage",
        },
      ],
    },
    "t_struct(Instrument)41434_storage": {
      encoding: "inplace",
      label: "struct Instrument",
      numberOfBytes: "128",
      members: [
        {
          astId: 41417,
          contract: "src/Exchange.sol:Exchange",
          label: "base",
          offset: 0,
          slot: "0",
          type: "t_address",
        },
        {
          astId: 41419,
          contract: "src/Exchange.sol:Exchange",
          label: "quote",
          offset: 0,
          slot: "1",
          type: "t_address",
        },
        {
          astId: 41421,
          contract: "src/Exchange.sol:Exchange",
          label: "baseLotExp",
          offset: 20,
          slot: "1",
          type: "t_uint8",
        },
        {
          astId: 41423,
          contract: "src/Exchange.sol:Exchange",
          label: "quoteLotExp",
          offset: 21,
          slot: "1",
          type: "t_uint8",
        },
        {
          astId: 41428,
          contract: "src/Exchange.sol:Exchange",
          label: "bids",
          offset: 0,
          slot: "2",
          type: "t_mapping(t_uint64,t_struct(Tick)41441_storage)",
        },
        {
          astId: 41433,
          contract: "src/Exchange.sol:Exchange",
          label: "asks",
          offset: 0,
          slot: "3",
          type: "t_mapping(t_uint64,t_struct(Tick)41441_storage)",
        },
      ],
    },
    "t_struct(Key)41376_storage": {
      encoding: "inplace",
      label: "struct Key",
      numberOfBytes: "64",
      members: [
        {
          astId: 41368,
          contract: "src/Exchange.sol:Exchange",
          label: "expiry",
          offset: 0,
          slot: "0",
          type: "t_uint40",
        },
        {
          astId: 41371,
          contract: "src/Exchange.sol:Exchange",
          label: "keyType",
          offset: 5,
          slot: "0",
          type: "t_enum(KeyType)5",
        },
        {
          astId: 41373,
          contract: "src/Exchange.sol:Exchange",
          label: "permissions",
          offset: 6,
          slot: "0",
          type: "t_uint16",
        },
        {
          astId: 41375,
          contract: "src/Exchange.sol:Exchange",
          label: "publicKey",
          offset: 0,
          slot: "1",
          type: "t_bytes_storage",
        },
      ],
    },
    "t_struct(Order)41415_storage": {
      encoding: "inplace",
      label: "struct Order",
      numberOfBytes: "32",
      members: [
        {
          astId: 41406,
          contract: "src/Exchange.sol:Exchange",
          label: "quantity",
          offset: 0,
          slot: "0",
          type: "t_uint64",
        },
        {
          astId: 41408,
          contract: "src/Exchange.sol:Exchange",
          label: "instrumentId",
          offset: 8,
          slot: "0",
          type: "t_uint64",
        },
        {
          astId: 41410,
          contract: "src/Exchange.sol:Exchange",
          label: "price",
          offset: 16,
          slot: "0",
          type: "t_uint64",
        },
        {
          astId: 41412,
          contract: "src/Exchange.sol:Exchange",
          label: "tickVolume",
          offset: 24,
          slot: "0",
          type: "t_uint32",
        },
        {
          astId: 41414,
          contract: "src/Exchange.sol:Exchange",
          label: "side",
          offset: 28,
          slot: "0",
          type: "t_uint8",
        },
      ],
    },
    "t_struct(QueuedMutation)41606_storage": {
      encoding: "inplace",
      label: "struct QueuedMutation",
      numberOfBytes: "192",
      members: [
        {
          astId: 41598,
          contract: "src/Exchange.sol:Exchange",
          label: "mutation",
          offset: 0,
          slot: "0",
          type: "t_enum(Mutation)41452",
        },
        {
          astId: 41600,
          contract: "src/Exchange.sol:Exchange",
          label: "mutationData",
          offset: 0,
          slot: "1",
          type: "t_bytes_storage",
        },
        {
          astId: 41603,
          contract: "src/Exchange.sol:Exchange",
          label: "sig",
          offset: 0,
          slot: "2",
          type: "t_struct(Signature)41595_storage",
        },
        {
          astId: 41605,
          contract: "src/Exchange.sol:Exchange",
          label: "enqueuedBlock",
          offset: 0,
          slot: "5",
          type: "t_uint256",
        },
      ],
    },
    "t_struct(Signature)41595_storage": {
      encoding: "inplace",
      label: "struct Signature",
      numberOfBytes: "96",
      members: [
        {
          astId: 41590,
          contract: "src/Exchange.sol:Exchange",
          label: "account",
          offset: 0,
          slot: "0",
          type: "t_bytes32",
        },
        {
          astId: 41592,
          contract: "src/Exchange.sol:Exchange",
          label: "keyId",
          offset: 0,
          slot: "1",
          type: "t_uint64",
        },
        {
          astId: 41594,
          contract: "src/Exchange.sol:Exchange",
          label: "rawSignature",
          offset: 0,
          slot: "2",
          type: "t_bytes_storage",
        },
      ],
    },
    "t_struct(State)41387_storage": {
      encoding: "inplace",
      label: "struct State",
      numberOfBytes: "64",
      members: [
        {
          astId: 41381,
          contract: "src/Exchange.sol:Exchange",
          label: "accounts",
          offset: 0,
          slot: "0",
          type: "t_mapping(t_bytes32,t_struct(Account)41404_storage)",
        },
        {
          astId: 41386,
          contract: "src/Exchange.sol:Exchange",
          label: "instruments",
          offset: 0,
          slot: "1",
          type: "t_mapping(t_uint64,t_struct(Instrument)41434_storage)",
        },
      ],
    },
    "t_struct(Tick)41441_storage": {
      encoding: "inplace",
      label: "struct Tick",
      numberOfBytes: "32",
      members: [
        {
          astId: 41436,
          contract: "src/Exchange.sol:Exchange",
          label: "quantity",
          offset: 0,
          slot: "0",
          type: "t_uint64",
        },
        {
          astId: 41438,
          contract: "src/Exchange.sol:Exchange",
          label: "remainingQuantity",
          offset: 8,
          slot: "0",
          type: "t_uint64",
        },
        {
          astId: 41440,
          contract: "src/Exchange.sol:Exchange",
          label: "volume",
          offset: 16,
          slot: "0",
          type: "t_uint32",
        },
      ],
    },
    t_uint16: { encoding: "inplace", label: "uint16", numberOfBytes: "2" },
    t_uint192: { encoding: "inplace", label: "uint192", numberOfBytes: "24" },
    t_uint256: { encoding: "inplace", label: "uint256", numberOfBytes: "32" },
    t_uint32: { encoding: "inplace", label: "uint32", numberOfBytes: "4" },
    t_uint40: { encoding: "inplace", label: "uint40", numberOfBytes: "5" },
    t_uint64: { encoding: "inplace", label: "uint64", numberOfBytes: "8" },
    t_uint8: { encoding: "inplace", label: "uint8", numberOfBytes: "1" },
  },
} as const satisfies StorageLayout;
